// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var stations: Stations {
        Stations(path: "/stations")
    }

    public struct Stations {
        /// Path: `/stations`
        public let path: String

        /// Get Stations list
        ///
        /// Endpoint https://api.marea.ooo/v2/stations for getting list of available Stations
        public var get: Request<[GetResponseItem]> {
            Request(path: path, method: "GET", id: "getStations")
        }

        public struct GetResponseItem: Decodable {
            /// Station ID
            ///
            /// Example: "TICON:cdc256d03b"
            public var id: String
            /// Station name
            ///
            /// Example: "Mawson, Australia"
            public var name: String
            /// Station latitude
            ///
            /// Example: -67.6
            public var latitude: Double
            /// Station longitude
            ///
            /// Example: 62.8833
            public var longitude: Double

            public init(id: String, name: String, latitude: Double, longitude: Double) {
                self.id = id
                self.name = name
                self.latitude = latitude
                self.longitude = longitude
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.id = try values.decode(String.self, forKey: "id")
                self.name = try values.decode(String.self, forKey: "name")
                self.latitude = try values.decode(Double.self, forKey: "latitude")
                self.longitude = try values.decode(Double.self, forKey: "longitude")
            }
        }
    }
}
